name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup API files
        uses: BadMagic100/setup-hk@v1
        with:
          apiPath: HKManaged
          dependencyFilePath: ModDependencies.txt
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Setup ms-build
        run: sudo apt-get install -y nuget mono-devel mono-xbuild
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Mod
        run: dotnet build -c Release
      - name: Upload Mod
        uses: actions/upload-artifact@v2
        with:
          name: HKVocal
          path: ./HKVocal/bin/Release
